# Generated by Django 4.0.1 on 2022-01-31 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 10, 8, 8, 704928, tzinfo=utc)),
        ),
    ]
