# Generated by Django 4.0.1 on 2022-01-31 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 10, 9, 35, 976268, tzinfo=utc)),
        ),
    ]
